repos:
-   repo: local
    hooks:
    -   id: validate-release-notes
        name: Validate Release Notes
        entry: python ci/check-release-notes.py
        language: python
        files: ^release-notes/.*\.yml$
