---
name: Print rollouts
on:
  pull_request:
    branches: [main]
    paths: ["updates/*.json"]
permissions:
  contents: read

jobs:
  print-rollouts:
    name: Print rollouts
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v2
      - name: Install dependencies
        run: sudo apt-get install python3-dateutil
      - name: Print rollouts
        run: make print-rollouts
