name: Validate Release Notes

on:
  pull_request:
    branches: [main]
    paths: ["release-notes/*.yml"]
    
jobs:
  validate:
    name: Validate Release Notes
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      
      - name: Validate Release Notes
        run: python ci/check-release-notes.py release-notes/next.yml release-notes/stable.yml release-notes/testing.yml
